# Site settings
title: Quotes
email: 
description: > # this means to ignore newlines until "baseurl:"
  Using Jekyll to create a cool repo of quotes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harshi.co/Quotes" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
